### PR TITLE
[MMR] Add Knight Profession

### PR DESCRIPTION
**Pull request by Theawesomeboophis**
Adds Knight Profession to Medieval Mod Reborn, 
Based on @squidboi937's PR linked here: https://github.com/CleverRaven/Cataclysm-DDA/pull/51148

### CODE REVIEW

**Comment by chaosvolt** [comment]
This is just a compilation copy of my mod: https://github.com/chaosvolt/cdda_medieval_mod_reborn

This change is either going to get overwritten when Kenan has to update from the source repo, or else it'll be a pain in the ass for them to try and preserve their additional changes every time. Either way, having the compilation be out of sync with the source mod is pretty bad.

Updates and proposals for mods should ideally go in the source repo first and be ported over to compilations afterward. If there are any essential updates my mods are missing, please make an issue pointing them out or PR it there first, because I can't find out about an important change I need to make if it's happening in some other repo and no one tells me about them.

As it stands, this idea could fit in the mod, although it already has an early-medieval man at arms profession. Since I do have late-medieval and a couple early-modern professions in the mod, if you PR it there I can take a look at it and see what'd be fitting to balance it relative to man-at-arms.

**Comment by Theawesomeboophis** [comment]
Sorry, I'll add all additions there in the future.

**Comment by chaosvolt** [comment]
No worries. Might work on porting it over myself when I get the chance, but might lower point cost and skills to better mesh well with the other high-tier professions.

On the plus side, for consistency I probably could give some of the other professions martial art traits too. Choice of swordsmanship or the polearm style for man at arms, possibly polearm style for viking (not sure), niten or sojutso for samurai...not sure. Though it might warrant ensuring professions that do get a martial art get a lil tweak to point cost in the end, we'll see.

**Comment by Kenan2000** [comment]
@Theawesomeboophis, @chaosvolt, @linonetwo, @321nick, @meelock Alright, based on Chaosvolt's advice that is beneficial, it's pretty weird to make content additions for mods author of which is active that are in my Modpacks before posting these addition pull requests on official author's GitHub page 

All contributors that want to make content additions for mods in my Modpacks that belong to either Chaosvolt, Axema, Zlorthishen, should first post these additions updates on their official GitHub pages 

All contributors that want to make fixes, tweaks updates for mods in my Modpacks for all kinds of authors, including but not only Chaosvolt, Axema, Zlorthishen, because these fixes, tweaks updates benefit both authors along with me, it is honestly advisable, greatly appreciated that you make pull requests for both official authors' repositories along with versions of these mods in my Modpacks, if you have any objections, difficulties making pull requests for both of us, it is very important that you make sure to ping both of us so that we can see that these mods are updated or require updates hopefully as well

**Comment by linonetwo** [comment]
Ok, so for mods in this list, we should first PR or issue to the original repo 

https://github.com/Kenan2000/CDDA-Kenan-Modpack#link-to-supporters-and-contributors-astoundingly-noice-works

Is this list complete?

**Pull request merged**
