### PR TITLE
feat: update arcana, for latest experimental feature and bug fix

### PR DESCRIPTION
**Pull request by linonetwo**
截屏2021-07-05 23 19 37

### CODE REVIEW

**Comment by linonetwo** [comment]
copy folder here from commit https://github.com/chaosvolt/cdda-arcana-mod/commit/7e96dea885697cb6b23d41dc7975d353121510f2

**Comment by Kenan2000** [comment]
@linonetwo Hey, thank you for this update, please don't just copy-paste updates like this, update only via latest commits, you see, there are a lot of unlinted files here along with old format of prices, etc, update only via specific commits, when you can, of course, as well

**Comment by linonetwo** [comment]
I still wonder why directly copy folder will cause lots of diffs, maybe this means we lost some previous commits from the Arcana repo?

**Comment by linonetwo** [comment]
If there are some unlinted file, maybe we can ask chaosvolt to lint them?

**Pull request closed without merging**
