### PR TITLE
[Fallout] Add Rad-X

### PR DESCRIPTION
**Pull request by Theawesomeboophis**
Adds Rad-X to the fallout mod, as I plan to expand how glowing deathclaws work, and also plan to add irradiated drinks and other comestibles from the fallout series.

### CODE REVIEW

**Comment by Theawesomeboophis** [comment]
Next PR will focus on glowing deathclaws, irradiated food, and sunset sarsaparilla.

**Comment by Kenan2000** [comment]
> Adds Rad-X to the fallout mod, as I plan to expand how glowing deathclaws work, and also plan to add irradiated drinks and other comestibles from the fallout series.

Good PR, it's just can you add this into either of medicine item groups so that it would actually spawn?Currently without recipes for it or being in an item group it's not gonna spawn at all pretty much

**Comment by Theawesomeboophis** [comment]
Ok, which group should I add it to? I know medicine spawns in bathrooms and
stuff, but I'm not sure the ID of the itemgroup.

**Comment by Theawesomeboophis** [comment]
Added it to drugs_rare, gonna test, make sure there's no errors, and then start working on the expansion.

**Comment by Theawesomeboophis** [comment]
Also want to make glowing ones heal from radiation, like they do in fallout, but not sure how to do that yet.

**Comment by Theawesomeboophis** [comment]
It loads, complained about stack size exceeding maximum, but I fixed it.

**Pull request merged**
