### PR TITLE
More and better fixes. Sierra Madre, F:NE, Rice Mod

### PR DESCRIPTION
**Pull request by calum12**
Did a whole bunch of learning and got quite a bit of help in the official discord and I feel like I understand how CDDA works a lot better now.
Likely going to have to start rewriting/updating parts to use more modern and conventional methods. 
These 3 mods no longer spit any errors but I haven't been able to extensively test and so things may not behave exactly as they were once intended, though any reports of such cases would be appreciated.

### CODE REVIEW

**Comment by Kenan2000** [comment]
@calum12 Thank you for the hard work that you're doing and providing the fixes and tweaks for OUR Modpack :-) , can you, please, clarify what exactly you've changed in `CDDA_Sierra_Madre_mod-master/items/ammo.json` and `CDDA_Sierra_Madre_mod-master/items/itemgroups.json`?

**Comment by calum12** [comment]
My apologies, I tried out the linter and didn't think about it masking my changes! lol.
The changes in `ammo.json` ... well I just realised that there is actually no change other than what the linter done to the layout 😨 sorry!
As for `itemgroups.json` the tweak was to ```  {
    "type": "item_group",
    "id": "ELIJAH_GUN",
    "subtype": "collection",
    "ammo": 50, // Changed this line **
    "entries": [ { "item": "gauss_rifle", "contents-item": "gauss_mag" } ]
  },```

** As for the changes to the line, it was originally 100 but would throw errors due to the magazine getting too full. At the default pocket data ammo_restriction for the magazine it would top out at 22.8 'ammo' so I tweaked the restriction a bit to get the number up from 22 and to stop the errors. I was getting help in the mod-dev channel in the official discord and the person agreed that the weapons are a bit wonky and should just be re-written to avoid hassle. They should function as is but might be a bit strange compared to what the original implementation idea was.

**Comment by calum12** [comment]
The Linter confused my git into thinking there was file changes 👍

**Comment by calum12** [comment]
Oooh, git codeblocks don't work like I thought, I think you can interpret it though 😆

**Comment by Kenan2000** [comment]
> My apologies, I tried out the linter and didn't think about it masking my changes! lol.
> The changes in `ammo.json` ... well I just realised that there is actually no change other than what the linter done to the layout 😨 sorry!
> As for `itemgroups.json` the tweak was to ` { "type": "item_group", "id": "ELIJAH_GUN", "subtype": "collection", "ammo": 50, // Changed this line ** "entries": [ { "item": "gauss_rifle", "contents-item": "gauss_mag" } ] },`
> 
> ** As for the changes to the line, it was originally 100 but would throw errors due to the magazine getting too full. At the default pocket data ammo_restriction for the magazine it would top out at 22.8 'ammo' so I tweaked the restriction a bit to get the number up from 22 and to stop the errors. I was getting help in the mod-dev channel in the official discord and the person agreed that the weapons are a bit wonky and should just be re-written to avoid hassle. They should function as is but might be a bit strange compared to what the original implementation idea was.

It's alright, mate, thank you for this, merging :-) would not have noticed many of these errors without your help

**Pull request merged**
