### PR TITLE
[ Magic Revamp] Fix Force Mage

### LINKED ISSUE #120: Bug during character creation (Magiclysm Revamp and Additions)
Experimental version: 8ce3dc5 (tiles)/Build: 2021-07-09-0030

 DEBUG    : Error: Json error: data/mods/MagicRevampAdditions/traits/attunements.json:137:23: Inline enchantment INLINE_ENCH_Force Mage_0 cannot be created as an enchantment already has this id.

    "prereqs": [ "MAGUS", "STORMSHAPER" ],
    "spells_learned": [ [ "force_blade", 5 ], [ "force_magical_armor", 5 ] ],
    "enchantments": [ {
                      ^
                        "condition": "ALWAYS", "values": [ { "value": "SPEED", "multiply": 0.2 } ] } ],
    "flags": [ "ATTUNEMENT" ]
  },

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 863
 VERSION  : 8ce3dc5

### PR DESCRIPTION
**Pull request by Theawesomeboophis**
Should fix #120

### CODE REVIEW

**Comment by Theawesomeboophis** [comment]
Closing as Kenan has fixed it, and fixed it better.

**Comment by Kenan2000** [comment]
@Theawesomeboophis Could you tell me your name on our discord server if you're present there hopefully? if I recall correctly, you've joined our server, if you have not, I really hope that you'll join our server EyRsVmBH
, I really appreciate work that you do as well

**Comment by Theawesomeboophis** [comment]
> @Theawesomeboophis Could you tell me your name on our discord server if you're present there hopefully? if I recall correctly, you've joined our server, if you have not, I really hope that you'll join our server EyRsVmBH
> , I really appreciate work that you do as well

I have not joined the server, and I don't like the social media feeling of discord, If I join the server, my name will be Theawesomeboophis or Boophis.

**Comment by Theawesomeboophis** [comment]
I'm not comfortable with Discord and would rather not join, I hope you understand, social media's just not my thing.

**Pull request closed without merging**
